server:
  port: 9000

spring:
  application:
    name: parcial_compiladores
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/realms/Peleas
          # URL para descargar las llaves públicas de validación
          jwk-set-uri: http://localhost:8080/realms/Peleas/protocol/openid-connect/certs
  datasource:
    url:  jdbc:postgresql://localhost:5432/club_peleas_db
    username: postgres
    password: 12345
    drive-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    defer-datasource-initialization: true
    properties:
      hibernate:
        format_sql: true
    sql:
      init:
        mode: always
        continue-on-error: false